export const SET_SELECTED_FIELD = "SET_SELECTED_FIELD"
export const FILL_FIELDS_LIST = "FILL_FIELDS_LIST"
export const FILL_USER_INFO = "FILL_USER_INFO"
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN"



